// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Week_1.Data;

#nullable disable

namespace Week_1.Migrations
{
    [DbContext(typeof(SmartLearnDbContext))]
    partial class SmartLearnDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Week_1.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentEnrollments")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Difficulty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<int>("MaxStudents")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CourseId");

                    b.ToTable("Courses", (string)null);

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            AverageRating = 0.0,
                            Category = "Programming",
                            CurrentEnrollments = 0,
                            Description = "Introduction to C# programming",
                            Difficulty = "Beginner",
                            InstructorId = 1,
                            MaxStudents = 200,
                            Title = "C# Basics"
                        },
                        new
                        {
                            CourseId = 2,
                            AverageRating = 0.0,
                            Category = "Programming",
                            CurrentEnrollments = 0,
                            Description = "Deep dive into LINQ queries",
                            Difficulty = "Advanced",
                            InstructorId = 1,
                            MaxStudents = 100,
                            Title = "Advanced LINQ"
                        },
                        new
                        {
                            CourseId = 3,
                            AverageRating = 0.0,
                            Category = "Design",
                            CurrentEnrollments = 0,
                            Description = "HTML and CSS fundamentals",
                            Difficulty = "Beginner",
                            InstructorId = 1,
                            MaxStudents = 150,
                            Title = "Web Design 101"
                        },
                        new
                        {
                            CourseId = 4,
                            AverageRating = 0.0,
                            Category = "Design",
                            CurrentEnrollments = 0,
                            Description = "User interface design principles",
                            Difficulty = "Intermediate",
                            InstructorId = 1,
                            MaxStudents = 80,
                            Title = "UI/UX Principles"
                        },
                        new
                        {
                            CourseId = 5,
                            AverageRating = 0.0,
                            Category = "Data",
                            CurrentEnrollments = 0,
                            Description = "Introduction to data science",
                            Difficulty = "Intermediate",
                            InstructorId = 1,
                            MaxStudents = 120,
                            Title = "Data Science Intro"
                        },
                        new
                        {
                            CourseId = 6,
                            AverageRating = 0.0,
                            Category = "Data",
                            CurrentEnrollments = 0,
                            Description = "ML algorithms and applications",
                            Difficulty = "Advanced",
                            InstructorId = 1,
                            MaxStudents = 60,
                            Title = "Machine Learning"
                        });
                });

            modelBuilder.Entity("Week_1.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("StudentUsername")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments", (string)null);
                });

            modelBuilder.Entity("Week_1.Instructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructorId"));

                    b.Property<DateTime>("DateRegistered")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InstructorId");

                    b.ToTable("Instructors", (string)null);

                    b.HasData(
                        new
                        {
                            InstructorId = 1,
                            DateRegistered = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "instructor@smartlearn.com",
                            IsActive = true,
                            Password = "pass123",
                            Username = "admin_instructor"
                        });
                });

            modelBuilder.Entity("Week_1.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<DateTime>("DateRegistered")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProgressPercentage")
                        .HasColumnType("float");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("Week_1.Enrollment", b =>
                {
                    b.HasOne("Week_1.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Week_1.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Week_1.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("Week_1.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
